name: flutterwave_standard
description: Flutterwave's official library that wraps the standard implementation.
version: 1.0.8
homepage: https://github.com/Flutterwave/flutter_standard
environment:
  sdk: ">=2.17.6 <4.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  fluttertoast: ^8.2.8
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  
flutter:
  generate: true
  uses-material-design: true
